# Generated by Django 6.0.6 on 2026-07-03 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_gallery_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nav_label', models.CharField(help_text='Short text shown in the navigation bar.', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('intro', models.TextField(blank=True)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nav_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pages/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='website.infopage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
